# Generated by Django 4.1.7 on 2023-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
